#8.CURRENT_DATE() & CURRENT_TIME()
CREATE TABLE TEST( 
	MYDATE DATE,
    MYTINE TIME,
	MYDATETIME DATETIME 
);
INSERT INTO TEST
VALUES ( current_date(),current_time(),now());
INSERT INTO TEST
VALUES ( current_date()+1,NULL,NULL);-- TOMMORROW 
INSERT INTO TEST
VALUES ( current_date()-1,NULL,NULL);-- YESTERDAY
INSERT INTO TEST
VALUES ( current_date(),current_time(),now()+INTERVAL 15 MINUTE);

SELECT * FROM TEST;

DROP table TEST; 
